### ISSUE TITLE
Terms & Conditions of Service

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#175]
This issue is to report that the terms & conditions that are returned to users of ICEES API instances are outdated and need to be updated.

**Comment by karafecho** [comment]
**ICEES+ Asthma API**

"Terms and Conditions of Service": "The Translator Integrated Clinical and Environmental Exposures Service (ICEES) is providing you with Data that have been de-identified in accordance with 45 C.F.R. §§ 164.514(a) and (b) of HIPAA and that UNC Health and the National Institute of Environmental Health Sciences permitted to provide under 45 C.F.R. § 164.502(d)(2). Recipient agrees to notify UNC Health via the Renaissance Computing Institute at UNC Chapel Hill in the event that Recipient receives any identifiable data in error and to take such measures to return the identifiable data and/or destroy it at the direction of UNC Health.\n\nRestrictions on Recipient’s Use of Data. Recipient further agrees to use the Data exclusively for the purposes and functionalities provided by the ICEES service: cohort discovery; feature-rich cohort discovery; hypothesis-driven queries; and exploratory queries. Recipient agrees to use appropriate safeguards to protect the Data from misuse and unauthorized access or disclosure. Recipient will report to UNC Health any unauthorized access, use, or disclosure of the Data not provided for by the Service of which Recipient becomes aware. Recipient will not attempt to identify the individuals whose information is contained in any Data transferred pursuant to this Service Agreement or attempt to contact those individuals. Recipient agrees not to sell the Data to any third party for any purpose. Recipient agrees not to disclose or publish the Data in any manner that would identify the Data as originating from UNC Health. Finally, Recipient agrees to reasonably limit the number of queries to the Service per IP address within a given time interval, in order to prevent rapid ‘attacks’ on the Service.\n\nWe kindly request that users of this service provide proper attribution for any secondary products (e.g., manuscripts, podium presentations, software) derived from the use of ICEES. Attribution should include acknowledgement of support from the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489, UL1TR002489-03S4] and the Clinical Research Branch, Intramural Research Program of the National Institute of Environmental Health Sciences, National Institutes of Health [ZID ES103354-01]. Please also acknowledge the Renaissance Computing Institute, UNC Health, UNC Hospitals, the Clinical Research Branch of the National Institute of Environmental Health Sciences, and any affiliated team members who contributed to the work.\n\nFor additional information or to report issues, please contact Karamarie Fecho (kfecho@renci.org).\n"

**ICEES+ DILI API**

"Terms and Conditions of Service": "The Translator Integrated Clinical and Environmental Exposures Service (ICEES) is providing you with Data that have been de-identified in accordance with 45 C.F.R. §§ 164.514(a) and (b) of HIPAA and that UNC Health and the Drug Induced Liver Injury Network are permitted to provide under 45 C.F.R. § 164.502(d)(2). Recipient agrees to notify UNC via the Renaissance Computing Institute (RENCI) at UNC Chapel Hill in the event that Recipient receives any identifiable data in error and to take such measures to return the identifiable data and/or destroy it at the direction of the Renaissance Computing Institute.\n\nRestrictions on Recipient’s Use of Data. Recipient further agrees to use the Data exclusively for the purposes and functionalities provided by the ICEES service: cohort discovery; feature-rich cohort discovery; hypothesis-driven queries; and exploratory queries. Recipient agrees to use appropriate safeguards to protect the Data from misuse and unauthorized access or disclosure. Recipient will report to UNC any unauthorized access, use, or disclosure of the Data not provided for by the Service of which Recipient becomes aware. Recipient will not attempt to identify the individuals whose information is contained in any Data transferred pursuant to this Service Agreement or attempt to contact those individuals. Recipient agrees not to sell the Data to any third party for any purpose. Recipient agrees not to disclose or publish the Data in any manner that would identify the Data as originating from UNC. Finally, Recipient agrees to reasonably limit the number of queries to the Service per IP address within a given time interval, in order to prevent rapid ‘attacks’ on the Service.\n\nWe kindly request that users of this service provide proper attribution for any secondary products (e.g., manuscripts, podium presentations, software) derived from the use of ICEES. Attribution should include acknowledgement of support from the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489, UL1TR002489-03S4] and the Drug Induced Liver Injury Network. Please also acknowledge the Renaissance Computing Institute, UNC Health, UNC Hospitals, the Drug Induced Liver Injury Network, and any affiliated team members who contributed to the work.\n\nFor additional information or to report issues, please contact Karamarie Fecho (kfecho@renci.org).\n"

**ICEES COVID API**
"Terms and Conditions of Service": "The Translator Integrated Clinical and Environmental Exposures Service (ICEES) is providing you with Data that have been de-identified in accordance with 45 C.F.R. §§ 164.514(a) and (b) of HIPAA and that UNC Health and the National Institute of Environmental Health Sciences are permitted to provide under 45 C.F.R. § 164.502(d)(2). Recipient agrees to notify UNC Health via the Renaissance Computing Institute at UNC Chapel Hill in the event that Recipient receives any identifiable data in error and to take such measures to return the identifiable data and/or destroy it at the direction of UNC Health.\n\nRestrictions on Recipient’s Use of Data. Recipient further agrees to use the Data exclusively for the purposes and functionalities provided by the ICEES service: cohort discovery; feature-rich cohort discovery; hypothesis-driven queries; and exploratory queries. Recipient agrees to use appropriate safeguards to protect the Data from misuse and unauthorized access or disclosure. Recipient will report to UNC Health any unauthorized access, use, or disclosure of the Data not provided for by the Service of which Recipient becomes aware. Recipient will not attempt to identify the individuals whose information is contained in any Data transferred pursuant to this Service Agreement or attempt to contact those individuals. Recipient agrees not to sell the Data to any third party for any purpose. Recipient agrees not to disclose or publish the Data in any manner that would identify the Data as originating from UNC Health. Finally, Recipient agrees to reasonably limit the number of queries to the Service per IP address within a given time interval, in order to prevent rapid ‘attacks’ on the Service.\n\nWe kindly request that users of this service provide proper attribution for any secondary products (e.g., manuscripts, podium presentations, software) derived from the use of ICEES. Attribution should include acknowledgement of support from the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489, UL1TR002489-03S4] and the Clinical Research Branch, Intramural Research Program of the National Institute of Environmental Health Sciences, National Institutes of Health [ZID ES103354-01]. Please also acknowledge the Renaissance Computing Institute, UNC Health, UNC Hospitals, the Clinical Research Branch of the National Institute of Environmental Health Sciences, and any affiliated team members who contributed to the work.\n\nFor additional information or to report issues, please contact Karamarie Fecho (kfecho@renci.org.\n"

**Comment by karafecho** [comment]
Add CoVar Applied Technologies and Copperline Professional Solutions to the acknowledgements for all ICEES instances.

**Comment by karafecho** [comment]
**Update to ICEES DILI API**

"Terms and Conditions of Service": "The Translator Integrated Clinical and Environmental Exposures Service (ICEES) is providing you with Data that have been de-identified in accordance with 45 C.F.R. §§ 164.514(a) and (b) of HIPAA and that UNC Health is permitted to provision under 45 C.F.R. § 164.502(d)(2) and that the Drug-Induced Liver Injury Network (DILIN) has agreed to expose. Recipient agrees to notify the Renaissance Computing Institute at UNC Chapel Hill in the event that Recipient receives any identifiable data in error and to take such measures to return the identifiable data and/or destroy it at the direction of UNC Health.\n\nRestrictions on Recipient’s Use of Data. Recipient further agrees to use the Data exclusively for the purposes and functionalities provided by the ICEES service: cohort discovery; feature-rich cohort discovery; hypothesis-driven queries; and exploratory queries. Recipient agrees to use appropriate safeguards to protect the Data from misuse and unauthorized access or disclosure. Recipient will report to UNC Health any unauthorized access, use, or disclosure of the Data not provided for by the Service of which Recipient becomes aware. Recipient will not attempt to identify the individuals whose information is contained in any Data transferred pursuant to this Service Agreement or attempt to contact those individuals. Recipient agrees not to sell the Data to any third party for any purpose. Recipient agrees not to disclose or publish the Data in any manner that would identify the Data as originating from UNC Health. Finally, Recipient agrees to reasonably limit the number of queries to the Service per IP address within a given time interval, in order to prevent rapid ‘attacks’ on the Service.\n\nWe require that users of this service provide proper attribution for any secondary products (e.g., manuscripts, podium presentations, software) derived from the use of ICEES. Attribution must include acknowledgement or, if appropriate, co-authorship of any individual person(s) who contributed significantly to secondary products resulting from use of this service. Attribution must further include acknowledgement of funding support from the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489] and the National Institute of Diabetes and Digestive and Kidney Diseases [1U01DK065201,1U01DK065193, 1U01DK065184, 1U01DK065211, 1U01DK065238 and 1U01DK065176]. All publications and secondary products must first be submitted to the Translator Publications Committee and the Drug-Induced Liver Injury Network Publications Committee for review and approval before they are finalized and released for public consumption.\n\nFor additional information such as the process for submitting secondary products for committee review, or to report issues, please contact Karamarie Fecho (kfecho@renci.org).\n"

**Comment by karafecho** [comment]
Note that development and production instances of ICEES+ asthma and ICEES+ DILI need to be updated.

**Comment by karafecho** [comment]
The following terms and conditions of service need to be added to the ICEES KG API instance as a revised 'JSON about dataset' operation or ideally as a new 'license, terms, and conditions of use' operation.

**ICEES KG API**

"Terms and Conditions of Service": "The Translator Integrated Clinical and Environmental Exposures Service (ICEES) is providing you with Data that have been de-identified in accordance with 45 C.F.R. §§ 164.514(a) and (b) of HIPAA and that UNC Health is permitted to provide under 45 C.F.R. § 164.502(d)(2). Recipient agrees to notify UNC Health via the Renaissance Computing Institute at UNC Chapel Hill in the event that Recipient receives any identifiable data in error and to take such measures to return the identifiable data and/or destroy it at the direction of UNC Health.\n\nRestrictions on Recipient’s Use of Data. Recipient further agrees to use the Data exclusively for the purposes and functionalities provided by the ICEES service: cohort discovery; feature-rich cohort discovery; hypothesis-driven queries; and exploratory queries. Recipient agrees to use appropriate safeguards to protect the Data from misuse and unauthorized access or disclosure. Recipient will report to UNC Health any unauthorized access, use, or disclosure of the Data not provided for by the Service of which Recipient becomes aware. Recipient will not attempt to identify the individuals whose information is contained in any Data transferred pursuant to this Service Agreement or attempt to contact those individuals. Recipient agrees not to sell the Data to any third party for any purpose. Recipient agrees not to disclose or publish the Data in any manner that would identify the Data as originating from UNC Health. Finally, Recipient agrees to reasonably limit the number of queries to the Service per IP address within a given time interval, in order to prevent rapid ‘attacks’ on the Service.\n\nWe require that users of this service provide proper attribution for any secondary products (e.g., manuscripts, podium presentations, software) derived from the use of ICEES. Attribution must include acknowledgement or, if appropriate, co-authorship of any individual person(s) who contributed significantly to secondary products resulting from use of this service. Attribution must further include acknowledgement of support from the National Center for Advancing Translational Sciences, National Institutes of Health [OT3TR002020, OT2TR003430, UL1TR002489, UL1TR002489-03S4], the Clinical Research Branch, Intramural Research Program of the National Institute of Environmental Health Sciences, National Institutes of Health [ZID ES103354-01], and the National Institute of Diabetes and Digestive and Kidney Diseases [5U01DK065201]. Please also acknowledge the Renaissance Computing Institute, the North Carolina Translational and Clinical Sciences Institute, the Clinical Research Branch of the National Institute of Environmental Health Sciences, and the Drug Induced Liver Injury Network, and any affiliated team members who contributed to the work. All publications and secondary products must first be submitted to the Translator Publications Committee for review and approval before they are finalized and released for public consumption.\n\nFor additional information such as the process for submitting secondary products for committee review, or to report issues, please contact Karamarie Fecho ([kfecho@renci.org](mailto:kfecho@renci.org).\n"

**Comment by karafecho** [comment]
Here's a link to the new wiki page for ICEES+ and ICEES KG terms and conditions of service: https://github.com/NCATSTranslator/Translator-All/wiki/ICEES--and-ICEES-KG-Terms-and-Conditions-of-Use.

**Comment by hyi** [comment]
@karafecho I found this page: https://github.com/NCATSTranslator/Translator-All/wiki/ICEES--and-ICEES-KG-Terms-and-Conditions-of-Use goes to a create new page site rather than showing the terms and conditions of use page. Can you check it to confirm if this is indeed the case? We will link to this page after it shows correctly rather than update the terms and conditions of use text in the swagger UI interface, right?

**Comment by karafecho** [comment]
Sorry, I pulled the wiki page from an ICEES KG response to a query that I ran last night on the ITRB instance, which appears to broken. As such, I pulled the correct wiki page from a test of ICEES KG that I ran a few weeks ago: https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES-and-ICEES-KG-Terms-and-Conditions-of-Use. Please use this one.

**Comment by hyi** [comment]
@karafecho Got it. I took a look at icees-api code and found terms and conditions are put in a terms.txt file which is loaded when the server is initially started to serve the swagger UI page. Should we keep the current approach to show terms and conditions or update it to hard code this wiki page link in the swagger UI page? I am fine with either approach since each has its own pro and con. Just let me know which way you think will work better to serve our use case and I will make the corresponding changes.

**Comment by karafecho** [comment]
Oh, yes, I forgot to mention the terms.txt file. In terms of how best to display the terms and conditions, I'm somewhat inclined to keep the current approach, if only to ensure that folks actually read them, but like you said, a hard-coded link to the wiki page has its pros, including that it provides cleaner output. I guess I'd vote to update the terms and conditions, but stick with the current approach.

**Comment by hyi** [comment]
@karafecho Have redeployed all icees dev and prod instances with updated terms and services along with the bug fix for feature association query when input value is zero under certain scenarios.

**Comment by karafecho** [comment]
I tested both fixes on icees-asthma-dev and icees-asthma-prod and all tests passed, so closing issue.
