### ISSUE TITLE
Deploy ICEES+ PCD API

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#191]
This issue is to create a timeline for deployment of an initial ICEES PCD instance. Also see [this issue](https://github.com/ResearchSoftwareInstitute/icees-data/issues/2).

For background, Hao generated an initial set of ICEES+ PCD integrated feature tables, although these are incomplete and erroneously include NIEHS EPR data. The identified data and binned deidentified data are still on Rockfish, which I do not have access to:

Rockfish ICEESPCD.zip (CLARK predictions) and PCD.zip (data): /opt/RENCI/output/FHIR
PCD dataset (N ≈ 8,000): /working_data/PCD (data), /working_data/ICEESPCD (CLARK predictions)
/share/spark/hao/data/PCD/EPR_binned/*de identified. (PCD)
/share/spark/hao/data/PCD/icees2_bins/*bins.json and (UNC Health bin values) /share/spark/hao/data/PCD/EPR_binned/EPR_binned_bins.json (EPR bin values).

Note that NCATS asked us to prioritize this use case prior to the September relay. As such, we probably need to prioritize this issue.

**Comment by hyi** [comment]
@karafecho I think this issue can be closed now that we have a PCD ICEES API deployed and registered.
