### ISSUE TITLE
Document deployment process

### ISSUE THREAD

**Issue by maximusunc** [ExposuresProvider/icees-api#227]
As we are redoing the deployment process, I think it would be a good idea to document the entire process.

**Comment by hyi** [comment]
@maximusunc Wondering whether the documentation here: https://github.com/helxplatform/translator-devops/blob/develop/helm/icees-api/Readme.md is sufficient to serve as the documentation of ICEES+ deployment process.

**Comment by maximusunc** [comment]
Yes, I think that's fine. When I opened this issue, I'm not sure we were using the kubernetes infrastructure, which has simplified the process quite a bit. Maybe just add a line or two in this repo's readme that explains that images are made on releases and that deployment happens in the translator-devops repo.

**Comment by hyi** [comment]
@maximusunc Good point. Have just created a [PR](https://github.com/ExposuresProvider/icees-api/pull/260) to add k8s deployment info to the readme file. See if it looks good. Thanks

**Comment by hyi** [comment]
Closing the issue as the PR has been approved and merged.
