### ISSUE TITLE
ICEES KG p_value returned as "empty / no value!" when very small

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#243]
This issue is to report that ICEES KG sometimes returns a `p_value` of `empty / no value!`, presumably when the P value is very small. An example is provided below for `Prednisone`.

**Query:**

```
{
  "nodes": {
    "n0": {
      "ids": [
        "MONDO:0004979"
      ],
      "categories": [
        "biolink:Disease"
      ],
      "is_set": false,
      "constraints": []
    },
    "n1": {
      "categories": [
        "biolink:ChemicalEntity"
      ],
      "is_set": false,
      "constraints": []
    }
  },
  "edges": {
    "e0": {
      "subject": "n0",
      "object": "n1",
      "predicates": [
        "biolink:has_real_world_evidence_of_association_with"
      ],
      "attribute_constraints": [],
      "qualifier_constraints": []
    }
  }
}

**Prednisone answer - edge attributes:**

```
<html><body>
<a class="attvalue" title="view ARAX synonyms" href="javascript:lookup_synonym('PUBCHEM.COMPOUND:5865',true)">PUBCHEM.COMPOUND:5865</a><span class="attvalue">----biolink:has_real_world_evidence_of_association_with----</span><a class="attvalue" title="view ARAX synonyms" href="javascript:lookup_synonym('MONDO:0004979',true)">MONDO:0004979</a><br><span class="fieldname">id: </span>urn:uuid:1cf29205-8d60-4cf1-9daf-1ec253f83a90<br>

 
--
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | chi_squared
value: | 5108.055269966048
 
attribute_type_id: | biolink:aggregator_knowledge_source
value_type_id: | biolink:InformationResource
original_attribute_name: | biolink:aggregator_knowledge_source
attribute_source: | infores:automat-icees-kg
value: | infores:automat-icees-kg
 
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | icees_cohort_identifier
value: | Asthma_UNC_PEGS_patient_2015_v4_binned_deidentified\|asthma\|2015\|2022_08_03_11_31_06
 
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | total
value: | 157920
 
attribute_type_id: | biolink:p_value
value_type_id: | EDAM:data_0006
original_attribute_name: | p_value
value: | -- empty / no value! --
 
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | object_feature_name
value: | ReactiveAirwayDx
 
attribute_type_id: | biolink:primary_knowledge_source
value_type_id: | biolink:InformationResource
original_attribute_name: | biolink:primary_knowledge_source
attribute_source: | infores:automat-icees-kg
value: | infores:icees-kg
 
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | terms_and_conditions_of_use
value: | https://github.com/NCATSTranslator/Translator-All/wiki/ICEES--and-ICEES-KG-Terms-and-Conditions-of-Use
 
attribute_type_id: | biolink:Attribute
value_type_id: | EDAM:data_0006
original_attribute_name: | subject_feature_name
value: | PrednisoneRx
 
attribute_type_id: | biolink:supporting_data_source
value_type_id: | EDAM:data_0006
original_attribute_name: | biolink:supporting_data_source
value: | https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES

</body>
</html>[PUBCHEM.COMPOUND:5865](javascript:lookup_synonym('PUBCHEM.COMPOUND:5865',true))----biolink:has_real_world_evidence_of_association_with----[MONDO:0004979](javascript:lookup_synonym('MONDO:0004979',true))
id: urn:uuid:1cf29205-8d60-4cf1-9daf-1ec253f83a90
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	chi_squared
value:	5108.055269966048
attribute_type_id:	biolink:aggregator_knowledge_source
value_type_id:	biolink:InformationResource
original_attribute_name:	biolink:aggregator_knowledge_source
attribute_source:	infores:automat-icees-kg
value:	infores:automat-icees-kg
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	icees_cohort_identifier
value:	Asthma_UNC_PEGS_patient_2015_v4_binned_deidentified|asthma|2015|2022_08_03_11_31_06
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	total
value:	157920
attribute_type_id:	biolink:p_value
value_type_id:	EDAM:data_0006
original_attribute_name:	p_value
value:	-- empty / no value! --
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	object_feature_name
value:	ReactiveAirwayDx
attribute_type_id:	biolink:primary_knowledge_source
value_type_id:	biolink:InformationResource
original_attribute_name:	biolink:primary_knowledge_source
attribute_source:	infores:automat-icees-kg
value:	infores:icees-kg
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	terms_and_conditions_of_use
value:	https://github.com/NCATSTranslator/Translator-All/wiki/ICEES--and-ICEES-KG-Terms-and-Conditions-of-Use
attribute_type_id:	biolink:Attribute
value_type_id:	EDAM:data_0006
original_attribute_name:	subject_feature_name
value:	PrednisoneRx
attribute_type_id:	biolink:supporting_data_source
value_type_id:	EDAM:data_0006
original_attribute_name:	biolink:supporting_data_source
value:	https://github.com/NCATSTranslator/Translator-All/wiki/Exposures-Provider-ICEES

```

**Comment by maximusunc** [comment]
Was this fixed with the latest updated PCD csv files?
