### ISSUE TITLE
Revert back to 0 vs 1 binning for Rx and Dx variables

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#246]
This issue is to document a need to revert back to 0 (no) vs 1 (yes) binning for all Rx and Dx variables. To make this change, both FHIR PIT and the all_feature YAML files will need to be revised.

Assigning Hong to FHIT PIT and Kara to all_features YAML files.

**Comment by hyi** [comment]
@karafecho I think this issue has been addressed, so can be closed.

**Comment by karafecho** [comment]
Agreed, closing issue.
