### ISSUE TITLE
Remove ICEES+ API KG endpoints

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#252]
This issue is to remove the multiple KG endpoints from each ICEES+ API instance, as they are no longer needed given ICEES KG and also outdates (TRAPI 1.2).

**Comment by hyi** [comment]
@karafecho This issue can be closed now that all ICEES+ production instances have been updated with KG related API endpoints removed.

**Comment by karafecho** [comment]
Agreed, closing issue.
