### ISSUE TITLE
Review SmartAPI registration update and merged PR and then redeploy ICEES+ API instances

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#253]
Max and I updated a bunch of SmartAPI registrations over the holiday break, including this one:  https://github.com/ExposuresProvider/icees-api/pull/251#pullrequestreview-1225041490. This issue is to request that you review the change and, if no additional changes are required, redeploy the ICEES+ API instances.

**Comment by hyi** [comment]
@karafecho I think this ticket can be closed now that the redeployed ICEES+ API instances have been verified.

**Comment by karafecho** [comment]
Agreed. I didn't test the production instances of the ICEES+ APIS, but I did test the four development instances (asthma, pcd, dili, covid) by creating a cohort and running a feature association functionality. All looks fine, so closing ticket.
