### ISSUE TITLE
Add odds ratios, Fisher's exact p values, and confidence intervals to ICEES+

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#256]
Please see related effort here: https://github.com/ExposuresProvider/icees-kg/issues/17, https://github.com/ExposuresProvider/icees-kg/issues/16, and https://github.com/ExposuresProvider/icees-kg/issues/15.

**Comment by hyi** [comment]
@karafecho Feel free to close this issue when you get a chance.

**Comment by karafecho** [comment]
Closing this issue, as Hong incorporated the new statistics, and I tested all new deployments, confirming that everything looks fine after a few small fixes.
