### ISSUE TITLE
year vs study_period

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#257]
This issue is intended to stimulate discussion and reach consensus on whether we should: (1) replace `study_period` with `year` in all FHIR PIT pipeline steps; (2) replace `year` with `study_period` in all FHIR PIT pipeline steps; or (3) maintain both `year` and `study_period`, but treating `study_period` as a feature variable.

Note that this issue has implications for FHIR PIT, icees db, icees api, and icees kg.

**Comment by hyi** [comment]
@karafecho Have created a PR and merged it to revert Hao's change in FHIR-PIT to revert study period and Active_In_Study_Period back to year and Active_In_Year to be compatible with ICEES+ APIs. Refer to the discussion in the issue #247 for more details regarding this decision.

**Comment by karafecho** [comment]
Closing issue, as fix was put in place.
