### ISSUE TITLE
Consider approaches for exposing the basic multivariate technique

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#264]
We recently developed an approach to create multivariate tables using the ICEES API and abiding by all federal and institutional regulations. This paper provides an overview of the general approach: https://pubmed.ncbi.nlm.nih.gov/35875189/. While the approach has limitations (e.g., data loss), we've proven that one can successfully apply various multivariate statistical analyses and machine learning algorithms to the multivariate table and largely replicate published findings.

I would like to find a way to create a new API endpoint to allow users to more readily apply this functionality. I had posted a ticket to the Translator Ops & WFs repo (see https://github.com/NCATSTranslator/OperationsAndWorkflows/issues/72), but it was deprioritized and moved to the TRAPI repo, I think.

This issue is to rethink options for exposing the ICEES open multivariate approach.

**Comment by hyi** [comment]
Add the [design spec Kara created for this](https://docs.google.com/presentation/d/1bJdSB2J9x8LhtsDr6ar7iy9PG9FjpaFksFU1sUnXf0k/edit#slide=id.p) as a reference for implementation.

**Comment by karafecho** [comment]
identified and are implementing an approach to support open longitudinal multivariate analysis by exposing and leveraging two key feature variables: `study_period` and `PatientID`. The latter approach will be tested initially using the ICEES+ PCD instance. 

Closing this issue as it has been replaced by #285 and #286.
