### ISSUE TITLE
TotalEDInpatientVisits, TotalEDVisits, TotalInpatientVisits - integers + enums

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#292]
This issue is to request that TotalEDInpatientVisits, TotalEDVisits, and TotalInpatientVisits be treated as integers with defined enumerations in all_feature YAML files for asthma, pcd, and covid instances. This will require (1) updates to the YAML files, (2) updates to the SQLite databases supporting each ICEES+ instance, and (3) redeployment of all three ICEES+ instances.

**Comment by hyi** [comment]
@karafecho I think this issue can be closed since we have the issue #297 to keep track of the one specific remaining issue related to this change.

**Comment by karafecho** [comment]
Closing issue per suggestion ...
