### ISSUE TITLE
log_odds_ratio_95_confidence_level is incorrectly labeled

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/icees-api#310]
I believe there is an existing ticket for this issue, which is to note that the `log_odds_ratio_95_confidence_level` that is being returned by ICEES is actually the `odds_ratio_95_confidence_level` or `fisher_exact_odds_ratio_95_confidence_level`. We need to (1) rename `log_odds_ratio_95_confidence_level` as `odds_ratio_95_confidence_level` or `fisher_exact_odds_ratio_95_confidence_level` and (2) add a new calculation for `log_odds_ratio_95_confidence_level`. (1) is a priority issue because I'd like to include a screenshot of the raw ICEES output in a paper I'm preparing (although I don't have to); (2) is not a priority issue because users can always calculate the confidence intervals themselves.

**Comment by hyi** [comment]
@karafecho Good catch. What if I make corrections to add log calculation for log_odds_ratio_conf_interval_95? Will it resolve both (1) and (2)?

**Comment by karafecho** [comment]
Your fix will work, although we'll be missing the confidence interval for `fisher_exact_odds_ratio`.

![image](https://github.com/ExposuresProvider/icees-api/assets/26254388/5f552751-2f86-4296-b8c2-e3b2c302885c)

**Comment by karafecho** [comment]
**Decision:** update calculation for log_odds_ratio_95_confidence_interval for accuracy and to align with the calculations used in icees-kg.

**Comment by karafecho** [comment]
Issue resolved, so closing ticket ...
